name: run-tests
on: [push, pull_request]
jobs:
  basic-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install mpmath flake8
      - run: flake8 sympy
      - run: bin/test --force-colors
