on:
  workflow_run:
    workflows: ["test"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo success............
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: runtests.yml
          workflow_conclusion: success
          name: benchmarks
      - run: cat pr_vs_master.txt
      - run: cat pr_num.txt

      - name: Read the pr_num file
        id: pr_num_reader
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: pr_num.txt

      - run: python -c 'print(repr(open("pr_num.txt").read()))'

      - name: Read the benchmark output
        id: pr_vs_master
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: pr_vs_master.txt

      - name: Find Comment
        if: ${{ steps.pr_num_reader.outputs.content != '' }}
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ steps.pr_num_reader.outputs.content }}
          comment-author: 'github-actions[bot]'
          body-includes: Build output

      - name: Create or update comment
        if: ${{ steps.pr_num_reader.outputs.content != '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ steps.pr_num_reader.outputs.content }}
          body: |
            Benchmarks
            ${{ steps.pr_vs_master.outputs.content }}
          edit-mode: replace

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo failure.............
