# ------------------------------------------------------------------ #
#                                                                    #
#           SymPy CI script for Github Actions                       #
#                                                                    #
#   Runs each time a pull request is opened, pushed or merged        #
#                                                                    #
# ------------------------------------------------------------------ #

name: test
on: [push, pull_request]
jobs:

  # -------------------- Run benchmarks against master ------------- #

  benchmarks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install asv virtualenv
      - run: git submodule add https://github.com/sympy/sympy_benchmarks.git

        # Need to make sure we can access the original master branch
      - run: git remote add upstream https://github.com/sympy/sympy.git
      - run: git fetch upstream master

      - run: asv machine --yes --config asv.conf.actions.json | tee pr_vs_master.txt
        #- run: asv run --config asv.conf.actions.json
        #- run: asv compare upstream/master HEAD --config asv.conf.actions.json --factor 1.5 | tee pr_vs_master.txt

      - name: Save the PR number in an artifact
        run: echo -n ${{ github.event.number }} > pr_num.txt

      - uses: actions/upload-artifact@v2
        with:
          name: benchmarks
          path: |
            pr_vs_master.txt
            pr_num.txt
